export const timeZones = [
    { label: "Baker Island Time (UTC-12)", value: "UTC-12" },
    { label: "Samoa Standard Time (UTC-11)", value: "UTC-11" },
    { label: "Hawaii-Aleutian Standard Time (UTC-10)", value: "UTC-10" },
    { label: "Alaska Standard Time (UTC-9)", value: "UTC-9" },
    { label: "Pacific Standard Time (UTC-8)", value: "UTC-8" },
    { label: "Mountain Standard Time (UTC-7)", value: "UTC-7" },
    { label: "Central Standard Time (UTC-6)", value: "UTC-6" },
    { label: "Eastern Standard Time (UTC-5)", value: "UTC-5" },
    { label: "Atlantic Standard Time (UTC-4)", value: "UTC-4" },
    { label: "Argentina Standard Time (UTC-3)", value: "UTC-3" },
    { label: "Fernando de Noronha Time (UTC-2)", value: "UTC-2" },
    { label: "Azores Standard Time (UTC-1)", value: "UTC-1" },
    { label: "Coordinated Universal Time (UTC)", value: "UTC" },
    { label: "West Africa Time (UTC+1)", value: "UTC+1" },
    { label: "Central Africa Time (UTC+2)", value: "UTC+2" },
    { label: "East Africa Time (UTC+3)", value: "UTC+3" },
    { label: "Gulf Standard Time (UTC+4)", value: "UTC+4" },
    { label: "Pakistan Standard Time (UTC+5)", value: "UTC+5" },
    { label: "Bangladesh Standard Time (UTC+6)", value: "UTC+6" },
    { label: "Indochina Time (UTC+7)", value: "UTC+7" },
    { label: "China Standard Time (UTC+8)", value: "UTC+8" },
    { label: "Japan Standard Time (UTC+9)", value: "UTC+9" },
    { label: "Australian Eastern Standard Time (UTC+10)", value: "UTC+10" },
    { label: "Solomon Islands Time (UTC+11)", value: "UTC+11" },
    { label: "New Zealand Standard Time (UTC+12)", value: "UTC+12" },
  ];
  